---
- hosts: webservers
  become: True
  tasks:
       - name: Pull latest nginx image
         docker_container:
                         name: "nginx-ansible-base"
                         image: "nginx:latest"
                         state: started
                         command: tail -f /dev/null
       - name: Add the nginx image to ansible hosts
         add_host:
                 name: "nginx-ansible-base"
                 ansible_connection: docker
                 ansible_ssh_user: root

- name: Configure nginx image for deploying websers
  hosts: "nginx-ansible-base"
  tasks:
        - name: Install Python3
          raw: apt update && apt upgrade -y && apt install python3 -y
        - name: Install Rsync
          apt:
             name: rsync
        - name: Copy local configuration Files to Nginx Conf
          synchronize:
                src: /home/ubuntu/new_project/
                dest: /usr/share/nginx/html/
        - name: Ensure NGINX Is enabled
          service:
                name: nginx
                enabled: yes
        - name: Clean up Python 3 and Prequisites
          raw: apt purge python3 rsync -y

- name: Snapshot base image to create newly configured Imafe
  hosts: webservers
  tasks:
    - name: Commit Docker image
      command: docker commit "nginx-ansible-base" "nginx-ansible-build-demo"

- name: Clean Up Docker Containers
  hosts: localhost
  tasks:
    - name: Remove Running Base Image
      docker_container:
                      name: nginx-ansible-base
                      state: absent
                      force_kill: yes




