---
- hosts: webservers
  become: True
  tasks:
       - name: Install apache server
         apt:
            name: apache
            state: present
       - name: Start Apache Server
         service:
                 name: apache
                 state: started
                 enabled: True
       - name: Deploy static website
         copy: 
             src: index.html
             dest: /var/www/html/


